server:
  port: 8080
  webflux:
    base-path: /api/v1
spring:
  application:
    name: "autenticacion-ms"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://:5432/postgres
    username: postgres
    password: admin
    host: localhost
    port: 5432
    database: postgres
    schema: public
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    io.r2dbc.postgresql: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.transaction: DEBUG
    root: INFO
